-- =====================================================================
-- Universidad Pontificia Bolivariana
-- Tópicos Avanzados de Bases de Datos - Periodo 202620
-- Examen No. 2 - Índices y Mejoras en el Desempeño de Consultas
-- Dominio: Análisis de Brechas de Seguridad
--
-- Script 01: implementación del modelo de datos (PostgreSQL)
-- Motor   : PostgreSQL 18.3 (Amazon RDS)
-- Adaptado desde el script original en MySQL.
-- Integrantes:
--           Camilo José Ardila Restrepo - ID 000543367
--           David Berrío Martínez       - ID 000547257
--
-- IMPORTANTE: este script se ejecuta conectado YA a la base
-- "brechas_seguridad" (creada en el script 00), logueado como
-- "postgres". No existe el comando USE de MySQL en PostgreSQL; cambiar
-- de base de datos siempre implica una conexión nueva.
--
-- Cambios de fondo respecto al original en MySQL:
--   - AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (se eligió
--     "BY DEFAULT" en vez de "ALWAYS" para permitir inserts con id
--     explícito en el script de carga de datos, si lo necesitan).
--   - ENGINE = InnoDB: no aplica en PostgreSQL, se elimina.
--   - INDEX inline dentro de CREATE TABLE: no existe en PostgreSQL;
--     cada índice se crea como una sentencia CREATE INDEX aparte,
--     después de la tabla correspondiente.
--   - REGEXP_LIKE(...) -> operador ~ (ya es case-sensitive, igual que
--     el flag 'c' del original).
--   - STATS_SAMPLE_PAGES (opción de tabla de MySQL): no existe en
--     PostgreSQL. El equivalente más cercano es correr ANALYZE después
--     de cargar los datos, o ajustar default_statistics_target por
--     columna con ALTER TABLE ... ALTER COLUMN ... SET STATISTICS n.
--     Se deja como comentario al final de la tabla puente.
--   - Todo el bloque de creación de tablas corre con
--     SET ROLE brechas_owner_role, para que las tablas queden con ese
--     rol como dueño (ver script 00) y así brechas_camilo/brechas_david
--     puedan crear índices sobre ellas sin ser superusuarios.
-- =====================================================================


-- Desde PostgreSQL 15, CREATE sobre el esquema "public" ya NO se
-- otorga a PUBLIC por defecto -- solo el dueño del esquema (postgres,
-- quien corrió el CREATE DATABASE en el script 00) puede crear objetos
-- ahí. Sin este GRANT, el SET ROLE de abajo falla con "permission
-- denied for schema public", porque SET ROLE adopta los privilegios
-- del rol destino (brechas_owner_role) y no conserva los de postgres.
GRANT CREATE ON SCHEMA public TO brechas_owner_role;

-- Las tablas quedarán con brechas_owner_role como dueño en vez de
-- postgres, para que camilo/david (miembros de ese rol) puedan crear
-- índices. postgres sigue siendo quien ejecuta el script.
SET ROLE brechas_owner_role;


-- =====================================================================
-- 2. SECUENCIAS
-- PostgreSQL sí implementa el objeto SEQUENCE nativamente, pero para
-- mantener el mismo patrón de llave subrogada simple del original, se
-- usa GENERATED ... AS IDENTITY, que internamente crea y gestiona una
-- secuencia por columna sin que haya que declararla aparte.
-- =====================================================================


-- =====================================================================
-- 3. TABLAS DE CATÁLOGO
-- =====================================================================

CREATE TABLE sector_economico (
    id_sector_economico     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_sector_economico VARCHAR(50) NOT NULL,
    CONSTRAINT pk_sector_economico PRIMARY KEY (id_sector_economico),
    CONSTRAINT uq_sector_economico_nombre UNIQUE (nombre_sector_economico)
);

CREATE TABLE pais (
    id_pais     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_pais VARCHAR(50) NOT NULL,
    CONSTRAINT pk_pais PRIMARY KEY (id_pais),
    CONSTRAINT uq_pais_nombre UNIQUE (nombre_pais)
);

CREATE TABLE vector_ataque (
    id_vector_ataque     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_vector_ataque VARCHAR(50) NOT NULL,
    CONSTRAINT pk_vector_ataque PRIMARY KEY (id_vector_ataque),
    CONSTRAINT uq_vector_ataque_nombre UNIQUE (nombre_vector_ataque)
);

CREATE TABLE severidad_incidente (
    id_severidad_incidente     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_severidad_incidente VARCHAR(20) NOT NULL,
    nivel_severidad_incidente  SMALLINT    NOT NULL,
    CONSTRAINT pk_severidad_incidente PRIMARY KEY (id_severidad_incidente),
    CONSTRAINT uq_severidad_incidente_nombre UNIQUE (nombre_severidad_incidente),
    CONSTRAINT uq_severidad_incidente_nivel UNIQUE (nivel_severidad_incidente),
    CONSTRAINT ck_severidad_incidente_nivel CHECK (nivel_severidad_incidente BETWEEN 1 AND 4)
);

CREATE TABLE categoria_sensibilidad (
    id_categoria_sensibilidad     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria_sensibilidad VARCHAR(20) NOT NULL,
    nivel_categoria_sensibilidad  SMALLINT    NOT NULL,
    CONSTRAINT pk_categoria_sensibilidad PRIMARY KEY (id_categoria_sensibilidad),
    CONSTRAINT uq_categoria_sensibilidad_nombre UNIQUE (nombre_categoria_sensibilidad),
    CONSTRAINT uq_categoria_sensibilidad_nivel UNIQUE (nivel_categoria_sensibilidad),
    CONSTRAINT ck_categoria_sensibilidad_nivel CHECK (nivel_categoria_sensibilidad BETWEEN 1 AND 4)
);


-- =====================================================================
-- 4. TABLAS DE ENTIDADES
-- =====================================================================

CREATE TABLE tipo_dato_expuesto (
    id_tipo_dato_expuesto     SMALLINT    GENERATED BY DEFAULT AS IDENTITY,
    nombre_tipo_dato_expuesto VARCHAR(50) NOT NULL,
    id_categoria_sensibilidad SMALLINT    NOT NULL,
    CONSTRAINT pk_tipo_dato_expuesto PRIMARY KEY (id_tipo_dato_expuesto),
    CONSTRAINT uq_tipo_dato_expuesto_nombre UNIQUE (nombre_tipo_dato_expuesto),
    CONSTRAINT fk_tipo_dato_categoria FOREIGN KEY (id_categoria_sensibilidad)
        REFERENCES categoria_sensibilidad (id_categoria_sensibilidad)
);

-- Etapa 3: ubica los tipos de dato de categoría crítica
CREATE INDEX idx_tipo_dato_categoria ON tipo_dato_expuesto (id_categoria_sensibilidad);


CREATE TABLE organizacion (
    id_organizacion              INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    nombre_organizacion          VARCHAR(100) NOT NULL,
    id_sector_economico          SMALLINT     NOT NULL,
    id_pais_organizacion         SMALLINT     NOT NULL,
    tamano_empleado_organizacion INTEGER      NOT NULL,
    CONSTRAINT pk_organizacion PRIMARY KEY (id_organizacion),
    CONSTRAINT uq_organizacion_nombre UNIQUE (nombre_organizacion),
    CONSTRAINT fk_organizacion_sector FOREIGN KEY (id_sector_economico)
        REFERENCES sector_economico (id_sector_economico),
    CONSTRAINT fk_organizacion_pais FOREIGN KEY (id_pais_organizacion)
        REFERENCES pais (id_pais),
    CONSTRAINT ck_organizacion_tamano CHECK (tamano_empleado_organizacion > 0)
);

CREATE INDEX idx_organizacion_sector ON organizacion (id_sector_economico);
CREATE INDEX idx_organizacion_pais   ON organizacion (id_pais_organizacion);


-- UQ1 (id_brecha_seguridad, id_organizacion): unicidad compuesta que
-- permite a la tabla puente referenciar la pareja (brecha, organización).
CREATE TABLE brecha_seguridad (
    id_brecha_seguridad              INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    codigo_brecha                    VARCHAR(10)   NOT NULL,
    id_organizacion                  INTEGER       NOT NULL,
    id_vector_ataque                 SMALLINT      NOT NULL,
    id_severidad_incidente           SMALLINT      NOT NULL,
    fecha_ocurrencia_brecha          DATE          NOT NULL,
    fecha_deteccion_brecha           DATE          NOT NULL,
    registros_afectados_total_brecha INTEGER       NOT NULL,
    costo_estimado_total_brecha      DECIMAL(15,2) NOT NULL,
    CONSTRAINT pk_brecha_seguridad PRIMARY KEY (id_brecha_seguridad),
    CONSTRAINT uq_brecha_seguridad_codigo UNIQUE (codigo_brecha),
    CONSTRAINT uq1_brecha_seguridad_organizacion UNIQUE (id_brecha_seguridad, id_organizacion),
    CONSTRAINT fk_brecha_organizacion FOREIGN KEY (id_organizacion)
        REFERENCES organizacion (id_organizacion),
    CONSTRAINT fk_brecha_vector FOREIGN KEY (id_vector_ataque)
        REFERENCES vector_ataque (id_vector_ataque),
    CONSTRAINT fk_brecha_severidad FOREIGN KEY (id_severidad_incidente)
        REFERENCES severidad_incidente (id_severidad_incidente),
    CONSTRAINT ck_brecha_fechas CHECK (fecha_deteccion_brecha >= fecha_ocurrencia_brecha),
    CONSTRAINT ck_brecha_registros CHECK (registros_afectados_total_brecha >= 0),
    CONSTRAINT ck_brecha_costo CHECK (costo_estimado_total_brecha >= 0)
);

CREATE INDEX idx_brecha_organizacion ON brecha_seguridad (id_organizacion);
CREATE INDEX idx_brecha_vector       ON brecha_seguridad (id_vector_ataque);
CREATE INDEX idx_brecha_severidad    ON brecha_seguridad (id_severidad_incidente);


-- Identificación seudonimizada: código, pseudónimo y hash MD5 del correo.
-- UQ1 (id_usuario, id_organizacion): idem patrón anterior.
CREATE TABLE usuario (
    id_usuario                 INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    codigo_usuario             VARCHAR(10) NOT NULL,
    pseudonimo_usuario         VARCHAR(50) NOT NULL,
    email_hash_usuario         CHAR(32)    NOT NULL,
    id_pais_residencia_usuario SMALLINT    NOT NULL,
    id_organizacion            INTEGER     NOT NULL,
    fecha_registro_usuario     DATE        NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_codigo UNIQUE (codigo_usuario),
    CONSTRAINT uq_usuario_pseudonimo UNIQUE (pseudonimo_usuario),
    CONSTRAINT uq_usuario_email_hash UNIQUE (email_hash_usuario),
    CONSTRAINT uq1_usuario_organizacion UNIQUE (id_usuario, id_organizacion),
    CONSTRAINT fk_usuario_pais FOREIGN KEY (id_pais_residencia_usuario)
        REFERENCES pais (id_pais),
    CONSTRAINT fk_usuario_organizacion FOREIGN KEY (id_organizacion)
        REFERENCES organizacion (id_organizacion),
    -- Equivalente a REGEXP_LIKE(..., 'c') de MySQL: ~ ya es case-sensitive
    CONSTRAINT ck_usuario_email_hash CHECK (email_hash_usuario ~ '^[0-9a-f]{32}$')
);

CREATE INDEX idx_usuario_pais         ON usuario (id_pais_residencia_usuario);
CREATE INDEX idx_usuario_organizacion ON usuario (id_organizacion);


-- =====================================================================
-- 5. TABLA PUENTE
-- Relación muchos a muchos entre brecha, usuario y tipo de dato.
--
-- id_organizacion se repite intencionalmente: las dos FK compuestas
-- (brecha, organización) y (usuario, organización) obligan a que la
-- organización de la brecha y la del usuario sean la misma.
-- =====================================================================
CREATE TABLE brecha_usuario_tipo_dato (
    id_brecha_seguridad        INTEGER  NOT NULL,
    id_usuario                 INTEGER  NOT NULL,
    id_tipo_dato_expuesto      SMALLINT NOT NULL,
    id_organizacion            INTEGER  NOT NULL,
    fecha_notificacion_usuario DATE     NOT NULL,
    CONSTRAINT pk_brecha_usuario_tipo_dato
        PRIMARY KEY (id_brecha_seguridad, id_usuario, id_tipo_dato_expuesto),
    CONSTRAINT fk_butd_brecha_organizacion FOREIGN KEY (id_brecha_seguridad, id_organizacion)
        REFERENCES brecha_seguridad (id_brecha_seguridad, id_organizacion),
    CONSTRAINT fk_butd_usuario_organizacion FOREIGN KEY (id_usuario, id_organizacion)
        REFERENCES usuario (id_usuario, id_organizacion),
    CONSTRAINT fk_butd_tipo_dato FOREIGN KEY (id_tipo_dato_expuesto)
        REFERENCES tipo_dato_expuesto (id_tipo_dato_expuesto)
);

-- Soporte de la FK compuesta hacia la brecha
CREATE INDEX idx_butd_brecha_organizacion
    ON brecha_usuario_tipo_dato (id_brecha_seguridad, id_organizacion);

-- Soporte de la FK compuesta hacia el usuario y, además, índice de
-- desempeño de la Etapa 4 (historial de un usuario ordenado por fecha
-- de notificación). A diferencia de InnoDB, un índice B-tree de
-- PostgreSQL NO incluye automáticamente la PK en las hojas; si en algún
-- ejercicio necesitan que el índice cubra la consulta sin tocar la
-- tabla (index-only scan), agreguen las columnas que falten con INCLUDE.
-- PG18 agregó "skip scan" para índices B-tree multicolumna: el
-- planificador ahora puede usar este índice de forma eficiente incluso
-- en consultas que filtran solo por id_organizacion o por
-- fecha_notificacion_usuario (sin filtrar por id_usuario, la columna
-- líder), algo que en versiones anteriores solía forzar un seq scan.
-- Útil para comparar planes de EXPLAIN en el examen.
CREATE INDEX idx_butd_usuario_org_fecha
    ON brecha_usuario_tipo_dato (id_usuario, id_organizacion, fecha_notificacion_usuario);

-- Soporte de la FK hacia el tipo de dato y, además, índice de
-- desempeño de la Etapa 3 ("la brecha expuso un dato crítico").
CREATE INDEX idx_butd_tipo_dato
    ON brecha_usuario_tipo_dato (id_tipo_dato_expuesto);

-- El STATS_SAMPLE_PAGES = 1000 del original (muestreo amplio para
-- ANALYZE) no existe como opción de tabla en PostgreSQL. El
-- equivalente es correr ANALYZE después de cargar los datos (script
-- 02), o subir el detalle de estadísticas por columna si hace falta:
-- ALTER TABLE brecha_usuario_tipo_dato ALTER COLUMN id_usuario SET STATISTICS 1000;


-- Vuelve al rol original de la sesión (postgres)
RESET ROLE;


-- =====================================================================
-- 6. VERIFICACIÓN
-- =====================================================================

-- Tablas creadas (deben ser 10)
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_catalog = 'brechas_seguridad'
ORDER BY table_name;

-- Llaves foráneas (incluidas las dos compuestas de la tabla puente)
-- GROUP_CONCAT (MySQL) -> STRING_AGG (PostgreSQL)
SELECT tc.table_name, tc.constraint_name,
       STRING_AGG(kcu.column_name, ',' ORDER BY kcu.ordinal_position) AS columnas,
       ccu.table_name AS referenced_table_name
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu
  ON tc.constraint_name = ccu.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
GROUP BY tc.table_name, tc.constraint_name, ccu.table_name
ORDER BY tc.table_name, tc.constraint_name;

-- Dueño de cada tabla (debe decir brechas_owner_role en las 10)
SELECT tablename, tableowner
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

-- SHOW GRANTS (MySQL) -> consulta sobre information_schema
SELECT grantee, table_name, privilege_type
FROM information_schema.role_table_grants
WHERE grantee IN ('brechas_camilo', 'brechas_david')
ORDER BY grantee, table_name, privilege_type;

-- Fin del script 01
